### ISSUE TITLE
Get users from empty account exception

### ISSUE THREAD

**Issue by amazing-space-invader** [secret-tech/backend-auth#62]
If tenant has no users, and trying get users list backend throws an exception
```
ReplyError: ERR wrong number of arguments for 'mget' command
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:303:14)
```

**Expected behavior** - backend responds with an empty array

**Comment by hlogeon** [comment]
👍
